# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_receiverhooks_download_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverhooks',
            name='is_backup',
            field=models.CharField(blank=True, default=b'1', help_text=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\xa4\x87\xe4\xbb\xbd\xe5\x8e\x9f\xe6\x9c\x89\xe9\x95\x9c\xe5\x83\x8f', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiverhooks',
            name='salt_minion_id',
            field=models.CharField(blank=True, help_text=b'\xe6\x93\x8d\xe4\xbd\x9c\xe4\xb8\xbb\xe6\x9c\xba', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='receiverhooks',
            name='target_docker_hub',
            field=models.CharField(blank=True, help_text=b'\xe7\x9b\xae\xe6\xa0\x87\xe9\x95\x9c\xe5\x83\x8f\xe5\xba\x93', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='receiverhooks',
            name='target_docker_hub_label',
            field=models.CharField(blank=True, help_text=b'\xe7\x9b\xae\xe6\xa0\x87\xe9\x95\x9c\xe5\x83\x8f\xe6\xa0\x87\xe7\xad\xbe', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='receiverhooks',
            name='target_docker_hub_password',
            field=models.CharField(blank=True, help_text=b'\xe7\x9b\xae\xe6\xa0\x87\xe9\x95\x9c\xe5\x83\x8f\xe5\xba\x93\xe7\x94\xa8\xe6\x88\xb7\xe5\xaf\x86\xe7\xa0\x81', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='receiverhooks',
            name='target_docker_hub_username',
            field=models.CharField(blank=True, help_text=b'\xe7\x9b\xae\xe6\xa0\x87\xe9\x95\x9c\xe5\x83\x8f\xe5\xba\x93\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d', max_length=300, null=True),
        ),
    ]
