# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20170907_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverhooks',
            name='push_docker_hub_content',
            field=models.TextField(blank=True, help_text=b'\xe5\x8f\x91\xe5\xb8\x83\xe9\x95\x9c\xe5\x83\x8f\xe8\xbf\x87\xe7\xa8\x8b', null=True),
        ),
        migrations.AddField(
            model_name='receiverhooks',
            name='push_docker_hub_time',
            field=models.DateTimeField(blank=True, help_text=b'\xe5\x8f\x91\xe5\xb8\x83\xe9\x95\x9c\xe5\x83\x8f\xe6\x97\xb6\xe9\x97\xb4', null=True),
        ),
    ]
