# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20170908_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiverhooks',
            name='env',
            field=models.CharField(choices=[(b'dev', b'\xe5\xbc\x80\xe5\x8f\x91\xe7\x8e\xaf\xe5\xa2\x83'), (b'fat', b'\xe6\xb5\x8b\xe8\xaf\x95\xe7\x8e\xaf\xe5\xa2\x83'), (b'pro', b'\xe6\xad\xa3\xe5\xbc\x8f\xe7\x8e\xaf\xe5\xa2\x83')], default=b'dev', help_text=b'\xe6\x89\x80\xe5\xb1\x9e\xe7\x8e\xaf\xe5\xa2\x83', max_length=255),
        ),
        migrations.AlterField(
            model_name='receiverhooks',
            name='target_docker_hub_label',
            field=models.CharField(blank=True, help_text=b'\xe5\xa4\x87\xe4\xbb\xbd\xe7\x9a\x84\xe9\x95\x9c\xe5\x83\x8f\xe6\xa0\x87\xe7\xad\xbe', max_length=300, null=True),
        ),
    ]
