# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20170913_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverhooks',
            name='load_docker_hub',
            field=models.CharField(blank=True, help_text=b'\xe8\xa2\xab\xe5\xaf\xbc\xe5\x85\xa5\xe7\x9a\x84\xe9\x95\x9c\xe5\x83\x8f', max_length=300, null=True),
        ),
    ]
